default: &default
  adapter: postgresql
  timeout: 5000
  pool: 5
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: so

test:
  <<: *default
  database: so_test